export default function GlaucusResponse({ message }) {
  if (!message) return null;

  // Function to parse and format the AI response
  const formatResponse = (text) => {
    // Split into sections if there are clear headings
    const sections = text.split(/\n(?=[A-Z][a-z]+:)/g);
    
    return sections.map((section, index) => {
      const [heading, ...content] = section.split(':');
      const isKeySection = heading.endsWith(')') || heading.includes('Species') || 
                          heading.includes('Characteristics') || heading.includes('Habitat');
      
      return (
        <div key={index} className="mb-4 last:mb-0">
          {heading && content.length > 0 && (
            <>
              <h3 className="font-semibold text-blue-700 mb-1 flex items-center">
                {isKeySection && (
                  <span className="mr-2">
                    {heading.includes('Species') ? '🐠' : 
                     heading.includes('Habitat') ? '🌊' : 
                     heading.includes('Characteristics') ? '🔍' : '📋'}
                  </span>
                )}
                {heading.trim()}
              </h3>
              <div className="pl-6 border-l-2 border-blue-100">
                <p className="text-gray-700 whitespace-pre-wrap">
                  {content.join(':').trim().replace(/\n/g, '\n\n')}
                </p>
              </div>
            </>
          )}
        </div>
      );
    });
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      <div className="bg-gradient-to-r from-blue-600 to-blue-500 px-6 py-3">
        <h2 className="text-lg font-semibold text-white flex items-center">
          <span className="mr-2">🐟</span>
          Glaucus AI Analysis
        </h2>
      </div>
      
      <div className="p-6 space-y-4">
        {formatResponse(message)}
        
        <div className="pt-4 mt-4 border-t border-gray-100">
          <p className="text-sm text-gray-500 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            This analysis is generated by AI and should be verified by marine experts
          </p>
        </div>
      </div>
    </div>
  );
}